resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.18-SNAPSHOT


resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/srirambtechit/artifactory-resource.git
      branch: main
  - name: artifactory
    type: artifactory-resource
    source:
      uri: ((sample-artifactory-uri))
      username: ((sample-artifactory-username))
      password: ((sample-artifactory-password))
      build_name: test-build

jobs:
  - name: build
    plan:
      - get: git-repo
      - task: build
        # file: git-repo/samples/simple/tasks/build.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openjdk
              tag: 8-jdk-alpine
          inputs:
          - name: git-repo
          outputs:
          - name: test
          run:
            path: sh
            user: root
            args:
            - | 
              -exc
              echo "Hello"
              ls -l
            # path: git-repo/samples/simple/scripts/build.sh
      - put: artifactory
        params:
          repo: example-repo-local
          folder: test
          build_uri: "((sample-concourse-uri))/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
          build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
  - name: test
    plan:
      - get: artifactory
        trigger: true
        passed: [build]
